"""empty message

Revision ID: 946663e6d120
Revises: c36efb4fd46a
Create Date: 2021-12-14 21:13:48.945925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946663e6d120'
down_revision = 'c36efb4fd46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('vin_num', sa.String(length=16), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('make', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=75), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserve')
    # ### end Alembic commands ###
