"""empty message

Revision ID: c15f007864d2
Revises: 946663e6d120
Create Date: 2021-12-15 16:29:33.387788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15f007864d2'
down_revision = '946663e6d120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_vin_num_key', 'inventory', type_='unique')
    op.drop_constraint('reserve_vin_num_key', 'reserve', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reserve_vin_num_key', 'reserve', ['vin_num'])
    op.create_unique_constraint('inventory_vin_num_key', 'inventory', ['vin_num'])
    # ### end Alembic commands ###
